.TH XL-AUTO 1 2015-08-05 20150805 xl-auto
.SH NAME
 xl-auto
.SH COPYRIGHT
 By Kyle Sallee in 2015 xl-auto was copyrighted.
.SH DESCRIPTION
 By xl-auto file ~/.config/xl or file /etc/xl is parsed.
 From lines that start with the word auto;
 a program name and parameters are read.
 Specified programs and parameters are invoked.
 xl-auto exits.
.SH AUTHOR
 Kyle Sallee
.SH LICENSE
 In the separate xl.7 manual page the software license is provided.
.SH SEE ALSO
.B man 1 xl
.SH FORKERS
