.TH xl-destroy 1 2015-08-05 20150805 xl-destroy
.SH NAME
 xl-destroy
.SH COPYRIGHT
 By Kyle Sallee in 2015 xl-destroy was copyrighted.
.SH DESCRIPTION
 The in pointer window is destroyed.
.SH PARAMETERS
 By -d or --destroy the pointer containing window         is destroyed.
 By -k or --kill    the pointer containing window process is killed.
.SH AUTHOR
 Kyle Sallee
.SH LICENSE
 In the separate xl.7 manual page the software license is provided.
.SH SEE ALSO
.B man 1 xl
.SH FORKERS
