.TH xl-download 1 2015-08-05 20150805 xl-download
.SH NAME
 xl-download
.SH COPYRIGHT
 By Kyle Sallee in 2015 xl-download was copyrighted.
.SH DESCRIPTION
 A down load file selection dialog is provided.
 Corefonts, firefox, flashplugin google-talkplugin can be downloaded.
.SH PARAMETERS
.SH EXAMPLES
.SH AUTHOR
 Kyle Sallee
.SH LICENSE
 In the separate xl.7 manual page the software license is provided.
.SH SEE ALSO
.B man 1 xl
.SH FORKERS
