.TH xl-firefox 1 2015-08-05 20150805 xl-firefox
.SH NAME
 xl-firefox
.SH COPYRIGHT
 By Kyle Sallee in 2015 xl-firefox was copyrighted.
.SH DESCRIPTION
 The Adobe Systems Incorporated provided flash player is downloaded.
 In directory ~/mozilla/plugins/ file libflashplayer.so is installed.
.SH PARAMETERS
.SH EXAMPLES
.SH AUTHOR
 Kyle Sallee
.SH BUGS
 Due to host server changes download might not succeed.
.SH LICENSE
 In the separate xl.7 manual page the software license is provided.
.SH SEE ALSO
.B man 1 xl
.SH FORKERS
