.TH XL-ROOT 1 2015-08-05 20150805 xl-root
.SH NAME
 xl-root
.SH COPYRIGHT
 By Kyle Sallee in 2015 xl-root was copyrighted.
.SH DESCRIPTION
 Ideally within the root window other mapped windows exist.
 Unfortunately, clutter can become.
 By clutter window contrast can be mitigated.
 Into a window other than desired
 unexpected input can become.
.PP
 The obvious solution follows.
 To the root window the amount of delegated windows must be reduced.
 To accomplish this task a new container window can be created.
.PP
 Concerning container windows;
 by use and interaction method;
 a name can be coined.
 Desks and sacks can be created.
.PP
 Desks and sacks are very different.
 And they are not incompatible.
 While a desk can not be sacked;
 to a desk a sack can be delegated.
 To explain each additional manual pages exist.
.SH AUTHOR
 Kyle Sallee
.SH LICENSE
 In the separate xl.7 manual page the software license is provided.
.SH SEE ALSO
.B man 1 xl
.B man 7 xl-desk.7
.B man 7 xl-sack.7
.SH FORKERS
