.TH xl-term 1 2015-08-05 20150805 xl-term
.SH NAME
 xl-term
.SH COPYRIGHT
 By Kyle Sallee in 2015 xl-term was copyrighted.
.SH DESCRIPTION
 /usr/bin/urxvt is invoked or /usr/bin/uxterm is invoked.
 If neither are installed the nothing happens.
 But rather than rewrite /usr/bin/xl-term
 ~/bin/xl-term can be modified.
 Provided ~/bin is in the PATH ahead of /usr/bin
 then ~/bin/xl-term will run.
 Otherwise ~/.config/xl can be modified.
 While better methods for invoking a terminal emulation program exist
 for invoking urxvt or xterm this wrapper suffices.
.SH PARAMETERS
 To the terminal emulation program invoked;
 all provided parameters are passed.
.SH EXAMPLES
.SH AUTHOR
 Kyle Sallee
.SH LICENSE
 In the separate xl.7 manual page the software license is provided.
.SH SEE ALSO
.B man 1 xl
.SH FORKERS
